/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    id("com.gradleup.shadow") version "8.3.5"
    `maven-publish`
}



dependencies {
    implementation(libs.com.github.kangarko.foundation)
    compileOnly("com.github.GAME-CLI-SRV-DEV:Slimefun-United-SlimefunX:26.2-1181c45e04-1")
}

tasks.shadowJar {
    dependencies {
        include(dependency("org.mineacademy:Foundation.*"))
        
        // 추가로 포함하고 싶은 다른 의존성이 있다면 아래와 같이 복사하여 추가할 수 있습니다.
        // include(dependency("com.example:my-library.*"))
    }

    // 2. 패키지 재배치 (Relocation) 설정
    val targetPackage = "${project.group}.${project.name}.lib"
    relocate("org.mineacademy.fo", targetPackage)
}


group = "me.CHANGEME"
version = "1.0.0"
description = "SlimefunAddon"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
