/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    id 'com.gradleup.shadow' version '8.3.5'
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.destroystokyo.com/repository/maven-public/")
    }

    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://jitpack.io")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.com.github.kangarko.foundation)
    api(libs.com.github.slimefun.united.slimefun.united.slimefun.united)
}

tasks.shadowJar {
    // 1. 이전 단계의 include 설정
    dependencies {
        include(dependency {
            moduleGroup == "org.mineacademy" && moduleName.startsWith("Foundation")
        })
     // include(dependency("org.slf4j:slf4j-api:"))
    }

    // 2. 패키지 재배치 (Relocation) 설정
    // Maven의 ${project.groupId}.${project.artifactId}.lib 구조를 그대로 반영합니다.
    val targetPackage = "${project.group}.${project.name}.lib"
    
    relocate("org.mineacademy.fo", targetPackage)
}



group = "me.CHANGEME"
version = "1.0.0"
description = "SlimefunAddon"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
