/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "SlimefunAddon"

dependencyResolutionManagement {
    // 1. 저장소 선언 위치 강제 규칙
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    
    // 2. 프로젝트 전체에 적용될 글로벌 저장소 목록
    repositories {
        mavenLocal()

        maven {
            url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
        }

        maven {
            url = uri("https://jitpack.io")
            metadataSources {
                artifact() 
            }
        }

        maven {
            url = uri("https://repo.maven.apache.org/maven2/")
        }

        maven {
            name = "minecraft-libraries"
            url = uri("https://libraries.minecraft.net")
        }

        maven {
            name = "mineacademy-repo"
            url = uri("https://bitbucket.org/kangarko/libraries/raw/master")
        }
    }
}
